#    Copyright (c) Perpetual Intelligence L.L.C. All Rights Reserved.
#
#    For license, terms, and data policies, go to:
#    https://terms.perpetualintelligence.com

name: build-test-publish

on:
  workflow_dispatch:

jobs:
  # chocolatey is only available on windows
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    env:
      PI_CI_REFERENCE: cross

    steps:
    
      # docs Repo
      - name: Checkout Docs
        uses: actions/checkout@v3
        with:
          path: main
                    
      # protocols repo
      - name: Checkout Shared
        uses: actions/checkout@v3
        with:
          repository: perpetualintelligence/shared
          path: shared
          
       # protocols repo
      - name: Checkout Cli
        uses: actions/checkout@v3
        with:
          repository: perpetualintelligence/cli
          path: cli
          token: ${{ secrets.PI_GITHUB_PAT }}
     
      # Print debug
      - name: Print
        if: ${{ false }}  # Debug
        run: |
          env
          ls -R
        shell: bash
        continue-on-error: false 
        
      # Setup .Net
      # Bug: Looks like the global.json is not getting picked by docfx build, so specify version explicitly
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.302'
      
      # Restore dependencies
      # Restore using specified nuget.config
      - name: Restore
        run: dotnet restore main/docfx_project/src/PerpetualIntelligence.Docs.Solution.sln --configfile main/nuget.config

      # Install chocolatey for PDF generation
      - name: Install wkhtmltopdf
        run: choco install wkhtmltopdf --no-progress
        continue-on-error: false

      # Install docfx
      - name: Setup docfc
        run: dotnet tool update -g docfx
        continue-on-error: false
  
      # Build docfx_project
      - name: Build
        run: docfx main/docfx_project/docfx.json
        continue-on-error: false

      # Push the docs/_site to the GitHub /docs dir 
      - name: Push
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: main/docfx_project/_site
          force_orphan: true