#    Copyright (c) Perpetual Intelligence L.L.C. All Rights Reserved.
#
#    For license, terms, and data policies, go to:
#    https://terms.perpetualintelligence.com

# Build the projects from multiple repos, generates the documentation and publishes static content.
name: build-test-publish

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # chocolatey is only available on windows
  build:
    runs-on: windows-latest
    timeout-minutes: 20
    #environment: github-release
    env:
      PI_CI_REFERENCE: cross

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # docs Repo
      - name: Checkout Docs
        uses: actions/checkout@v2
        with:
          path: main
                    
      # protocols repo
      - name: Checkout Protocols
        uses: actions/checkout@v2
        with:
          repository: perpetualintelligence/protocols
          path: protocols
          
       # protocols repo
      - name: Checkout Cli
        uses: actions/checkout@v2
        with:
          repository: perpetualintelligence/cli
          path: cli
          token: ${{ secrets.PI_GITHUB_PAT }}
     
      # Print debug
      - name: Print
        if: ${{ false }}  # Debug
        run: |
          env
          ls -R
        shell: bash
        continue-on-error: false 
        
      # Setup .Net
      # Bug: Looks like the global.json is not getting picked by docfx build, so specify version explicitly
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.300'
      
      # Restore dependencies
      # Restore using specified nuget.config
      - name: Restore
        run: dotnet restore main/docfx_project/src/PerpetualIntelligence.Docs.Solution.sln --configfile main/nuget.config

      # Install chocolatey for PDF generation
      - name: Install wkhtmltopdf
        run: |
          choco install wkhtmltopdf --no-progress
        
      # Docfx build
      # 1. Install docfx via Nuget
      # 2. Build
      - name: Docfx build
        run: |
          nuget install docfx.console -Version 2.59.2
          docfx.console.2.59.2/tools/docfx.exe main/docfx_project/docfx.json
        continue-on-error: false

      # Push the docs/_site to the GitHub /docs dir 
      - name: Push
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: main/docfx_project/_site
          force_orphan: true
