#    Copyright 2021 Perpetual Intelligence L.L.C. All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0.
#    https://github.com/perpetualintelligence/terms/blob/main/LICENSE
#
#    Additional terms and policies.
#    https://github.com/perpetualintelligence/terms/blob/main/policies.md

# Downloads the latest release, extract and publish documentation to GitHub pages.

name: push-gh-branch

# Controls when the workflow will run
on:
  # Triggers a new release is released. The workflow will no trigger for preview releases.
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Download latest release
      - name: Download release
        uses: dsaltares/fetch-gh-release-asset@0.06
        with:
          repo: perpetualintelligence/docs
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          file: PerpetualIntelligence.Docs.Site.zip
          target: docfx/PerpetualIntelligence.Docs.Site.zip
          
      - name: Show dir
        run: ls -R

      ## Unzip docs
      ## https://github.com/montudor/action-zip
      #- uses: montudor/action-zip@v1
      #  with:
      #    args: unzip -qq ${{ github.workspace }}/docfx/PerpetualIntelligence.Docs.Site.zip -d ${{ github.workspace }}/docfx/_site
      
      #- name: Show dir
      #  run: ls -R ${{ github.workspace }}
